# Generated by Django 3.2.6 on 2021-09-01 11:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_customuser_uuid_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='uuid_id',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
